### ISSUE TITLE
Decoder class for "ExtrinsicMetadata" not found

### ISSUE THREAD

**Issue by ayeteng** [polkascan/py-substrate-interface#11]
I connect to a private substrate node where I use docker to build it.
`> docker run -p 9944:9944 -it --rm  parity/substrate:latest --dev --ws-external --rpc-external
`
and try the code below:

```
import substrateinterface
substrate = substrateinterface.SubstrateInterface(url="ws://127.0.0.1:9944/")
block_hash = substrate.get_block_hash(1)
print(block_hash)
get_runtime_block = substrate.get_runtime_block(block_hash=None)
```
I can get the hash of block 1 but I cannot get runtime block. The error message shows "ExtrinsicMetadata" not found. Is this issue with substrate?

`>python3 poe_access.py
0xfc496269de21da17235e69329d33411805e1564f968a12f8522f8c257c850665
Traceback (most recent call last):
  File "poe_access.py", line 6, in <module>
    get_runtime_block = substrate.get_runtime_block(block_hash=None)
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/substrateinterface/__init__.py", line 1226, in get_runtime_block
    self.init_runtime(block_hash=block_hash, block_id=block_id)
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/substrateinterface/__init__.py", line 565, in init_runtime
    self.metadata_decoder = self.get_block_metadata(block_hash=self.block_hash, decode=True)
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/substrateinterface/__init__.py", line 301, in get_block_metadata
    metadata_decoder.decode()
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/scalecodec/base.py", line 278, in decode
    self.value = self.process()
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/scalecodec/metadata.py", line 49, in process
    self.metadata = self.process_type(self.version.value)
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/scalecodec/base.py", line 352, in process_type
    obj.decode(check_remaining=False)
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/scalecodec/base.py", line 278, in decode
    self.value = self.process()
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/scalecodec/metadata.py", line 968, in process
    result_data["metadata"]["MetadataV11"]["extrinsic"] = self.process_type("ExtrinsicMetadata").value
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/scalecodec/base.py", line 351, in process_type
    obj = self.get_decoder_class(type_string, self.data, **kwargs)
  File "/home/ubuntu/work/python_trek_env/lib/python3.6/site-packages/scalecodec/base.py", line 347, in get_decoder_class
    raise NotImplementedError('Decoder class for "{}" not found'.format(type_string))
NotImplementedError: Decoder class for "ExtrinsicMetadata" not found
`

**Comment by ayeteng** [comment]
replace the line 
`substrate = substrateinterface.SubstrateInterface(url="ws://127.0.0.1:9944/")
`
to 
`substrate = substrateinterface.SubstrateInterface(url="http://127.0.0.1:9933/", address_type=42, type_registry_preset='kusama')`
that solve the issue.

How can I generate my own type_registry_preset?

**Comment by arjanz** [comment]
Basically a type registry is a JSON file with a structure like: https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/kusama.json

Besides this network specific types or exceptions, the default Substrate types are also loaded (https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/default.json)

I think the easiest way to experiment and use your own types for your own runtime, create a new JSON file somewhere and load that type registry as follows:

```
from scalecodec.type_registry import load_type_registry_file
from substrateinterface import SubstrateInterface

substrate = SubstrateInterface(
    url="http://127.0.0.1:9933",
    address_type=42,
    type_registry=load_type_registry_file("/path/to/custom.json"),
)
```

Note that in your previous comment if you change it to:
`substrate = substrateinterface.SubstrateInterface(url="ws://127.0.0.1:9944/", type_registry_preset='default')` it would also work, probably it's better to make this default behaviour in the future to avoid confusion.

Type registry presets are basically JSON files that are shipped with the SCALE-codec.

**Comment by arjanz** [comment]
Fixed type registry entry ExtrinsicMetadata -> ExtrinsicsMetadata
