### ISSUE TITLE
scalecodec.exceptions.RemainingScaleBytesNotEmptyException when running balance_transfer.py

### ISSUE THREAD

**Issue by kwikiel** [polkascan/py-substrate-interface#119]
`scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Decoding "U128" - No more bytes available (needed: 76 / total: 72)`

To reproduce
1) Git clone the repository 
2) Run ./start_local_substrate_node.sh  to set up a blockchain 

Full error: 
```

Traceback (most recent call last):
  File "balance_transfer.py", line 34, in <module>
    account_info = substrate.query('System', 'Account', params=[keypair.ss58_address])
  File "/home/kacper/.local/lib/python3.8/site-packages/substrateinterface/base.py", line 1501, in query
    obj.decode()
  File "/home/kacper/.local/lib/python3.8/site-packages/scalecodec/base.py", line 428, in decode
    self.value = self.process()
  File "/home/kacper/.local/lib/python3.8/site-packages/scalecodec/types.py", line 461, in process
    result[key] = self.process_type(data_type, metadata=self.metadata).value
  File "/home/kacper/.local/lib/python3.8/site-packages/scalecodec/base.py", line 491, in process_type
    obj.decode(check_remaining=False)
  File "/home/kacper/.local/lib/python3.8/site-packages/scalecodec/base.py", line 428, in decode
    self.value = self.process()
  File "/home/kacper/.local/lib/python3.8/site-packages/scalecodec/types.py", line 461, in process
    result[key] = self.process_type(data_type, metadata=self.metadata).value
  File "/home/kacper/.local/lib/python3.8/site-packages/scalecodec/base.py", line 491, in process_type
    obj.decode(check_remaining=False)
  File "/home/kacper/.local/lib/python3.8/site-packages/scalecodec/base.py", line 437, in decode
    raise RemainingScaleBytesNotEmptyException(
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Decoding "U128" - No more bytes available (needed: 76 / total: 72)
```

Maybe it's something trivial and I would like to fix it but I would need some guidance in helping me where to look for the solution.

**Comment by arjanz** [comment]
There was indeed an issue with the versioning info in the type registry, this will be fixed in next release. Or you can use the `use_remote_preset=True` or `substrate.reload_type_registry()` as described in https://github.com/polkascan/py-substrate-interface#keeping-type-registry-presets-up-to-date to download these updates to your local file system.

I will also update the Docker image to a more recent version of Substrate in `start_local_substrate_node.sh`

Thanks for pointing this out.
