### ISSUE TITLE
NotImplementedError: Type '{'def': {'sequence': {'type': 1}}}' not supported

### ISSUE THREAD

**Issue by facorazza** [polkascan/py-substrate-interface#135]
I'm running substrate-interface v1.0.2
```
Traceback (most recent call last):
  File "/home/f/.local/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/f/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/f/.local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/f/.local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/f/.local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/f/.local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/f/project-tracking-platform/webapp/auth.py", line 101, in wrapped_view
    return view(**kwargs)
  File "/home/f/project-tracking-platform/webapp/project.py", line 58, in new
    contract_address = substrate.upload_contract(
  File "/home/f/project-tracking-platform/substrate_wrapper.py", line 43, in upload_contract
    code = ContractCode.create_from_contract_files(
  File "/home/f/.local/lib/python3.8/site-packages/substrateinterface/contracts.py", line 486, in create_from_contract_files
    metadata = ContractMetadata.create_from_file(metadata_file, substrate=substrate)
  File "/home/f/.local/lib/python3.8/site-packages/substrateinterface/contracts.py", line 69, in create_from_file
    return cls(json.loads(metadata_string), substrate)
  File "/home/f/.local/lib/python3.8/site-packages/substrateinterface/contracts.py", line 50, in __init__
    self.__parse_type_registry()
  File "/home/f/.local/lib/python3.8/site-packages/substrateinterface/contracts.py", line 107, in __parse_type_registry
    self.type_registry[idx] = self.get_type_string_for_metadata_type(idx)
  File "/home/f/.local/lib/python3.8/site-packages/substrateinterface/contracts.py", line 257, in get_type_string_for_metadata_type
    raise NotImplementedError(f"Type '{arg_type}' not supported")
NotImplementedError: Type '{'def': {'sequence': {'type': 1}}}' not supported
```

The connection is initialized as:
```
substrate = SubstrateInterface(
    url="ws://127.0.0.1:9944",
    ss58_format=42,
    type_registry_preset="canvas"
)
keypair = Keypair.create_from_uri('//Alice')

# Upload WASM code
code = ContractCode.create_from_contract_files(
    metadata_file=metadata_filepath,
    wasm_file=wasm_filepath,
    substrate=substrate
)

# Deploy contract
contract = code.deploy(
    keypair=keypair,
    endowment=endowment,
    gas_limit=gas_limit,
    constructor=constructor,
    args=args,
    deployment_salt=str(time_ns()),
    upload_code=upload_code
)
```

**Comment by facorazza** [comment]
Could it be that vector containers in smart contracts are not supported?

**Comment by arjanz** [comment]
New ink metadata support added since https://github.com/polkascan/py-substrate-interface/releases/tag/v1.0.6
