### ISSUE TITLE
hi, sir i have a new question. "AttributeError: 'NoneType' object has no attribute 'split'"

### ISSUE THREAD

**Issue by Yxiaoyang** [polkascan/py-substrate-interface#139]
i want query "Staking.ErasRewardPoints" for polkadot. but it's wrong.

this my code:
`substrate.query(module='Staking', storage_function='ErasRewardPoints', params=[498],)`

this is traceback:
`Traceback (most recent call last):
  File "C:\Users\aa\Desktop\crust\polkadot-node\polka_subrate.py", line 59, in <module>
    print(substrate.query(module='Staking', storage_function='ErasRewardPoints', params=[498], block_hash='0x2cbe577f3e372a4ef75abc0e15930a50ead166ae721c8b09e34d94b5d9ffc383'))
  File "C:\Users\aa\Desktop\crust\venv\lib\site-packages\substrateinterface\base.py", line 1316, in query
    obj.decode()
  File "C:\Users\aa\Desktop\crust\venv\lib\site-packages\scalecodec\base.py", line 658, in decode
    self.value_serialized = self.process()
  File "C:\Users\aa\Desktop\crust\venv\lib\site-packages\scalecodec\types.py", line 471, in process
    field_obj = self.process_type(data_type, metadata=self.metadata)
  File "C:\Users\aa\Desktop\crust\venv\lib\site-packages\scalecodec\base.py", line 740, in process_type
    obj = self.runtime_config.create_scale_object(type_string, self.data, **kwargs)
  File "C:\Users\aa\Desktop\crust\venv\lib\site-packages\scalecodec\base.py", line 156, in create_scale_object
    return decoder_class(data=data, **kwargs)
  File "C:\Users\aa\Desktop\crust\venv\lib\site-packages\scalecodec\types.py", line 1674, in __init__
    sub_type_parts = [x.strip() for x in self.sub_type.split(',')]
AttributeError: 'NoneType' object has no attribute 'split'`

Is it because the Polkadot version has been upgraded? It was normal before

thanks for much to u

**Comment by arjanz** [comment]
There was a problem parsing `BTreeMap` types icm `MetadataV14` runtimes, will be fixed in next release of `scalecodec`. Thanks for reporting!

**Comment by arjanz** [comment]
https://github.com/polkascan/py-scale-codec/releases/tag/v1.0.8
