### ISSUE TITLE
KSM Proxy Extrinsic not working

### ISSUE THREAD

**Issue by ybstaked** [polkascan/py-substrate-interface#394]
Hey, using python substrate-interface==1.7.9 and getting this error for the proxy extrinsic. Anyone have any suggestions or seen it before?

```
Failed to send extrinsic: {'code': 1002, 'message': 'Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x6616 - <unknown>!rust_begin_unwind\n    1: 0x312a - <unknown>!core::panicking::panic_fmt::hbb5a6b42001bdfec\n    2: 0x5ad90a - <unknown>!TaggedTransactionQueue_validate_transaction', 'data': 'RuntimeApi("Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\\nWASM backtrace:\\nerror while executing at wasm backtrace:\\n    0: 0x6616 - <unknown>!rust_begin_unwind\\n    1: 0x312a - <unknown>!core::panicking::panic_fmt::hbb5a6b42001bdfec\\n    2: 0x5ad90a - <unknown>!TaggedTransactionQueue_validate_transaction")'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/manager/docker/nomination-manager/nomination_manager/__main__.py", line 462, in <module>
    main()
  File "/home/manager/docker/nomination-manager/nomination_manager/__main__.py", line 457, in main
    run_nomination_manager(args, chain, config)
  File "/home/manager/docker/nomination-manager/nomination_manager/__main__.py", line 296, in run_nomination_manager
    if receipt.is_success:
AttributeError: 'NoneType' object has no attribute 'is_success'

```

**Comment by malingzhao** [comment]
substrateinterface.exceptions.SubstrateRequestException: {'code': 1002, 'message': 'Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x6616 - <unknown>!rust_begin_unwind\n    1: 0x312a - <unknown>!core::panicking::panic_fmt::hbb5a6b42001bdfec\n    2: 0x5ad90a - <unknown>!TaggedTransactionQueue_validate_transaction', 'data': 'RuntimeApi("Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\\nWASM backtrace:\\nerror while executing at wasm backtrace:\\n    0: 0x6616 - <unknown>!rust_begin_unwind\\n    1: 0x312a - <unknown>!core::panicking::panic_fmt::hbb5a6b42001bdfec\\n    2: 0x5ad90a - <unknown>!TaggedTransactionQueue_validate_transaction")'}
I has the err too

**Comment by pmensik** [comment]
I am having the same error too, the same goes for Polkadot unfortunately.

**Comment by arjanz** [comment]
Can you supply example code and target runtime + version, so I can run some tests?

**Comment by pmensik** [comment]
@arjanz Sure thing. Target runtime is the current version of Kusama (but also tried Polkadot with the same result). Version of `substrate-interface` is 1.5.0.

```
unbond_call = substrate.compose_call(
                                  call_module   = "Staking",
                                  call_function = "unbond",
                                  call_params   = {
                                    "value": amount 
                                  }
                              )
proxy_call = substrate.compose_call(
    call_module   = "Proxy",
    call_function = "proxy",
    call_params   = {
      "real":             validator,
      "force_proxy_type": None,
      "call":             unbond_call
      # I tried also unbond_call.serialiaze() or substrate.create_unsigned_extrinsic(unbond_call).serialize()
    }
  )
extrinsic = substrate.create_signed_extrinsic(call=proxy_call, keypair=staking_proxy)
  print(extrinsic)
  try:
    # Send the call
    receipt = substrate.submit_extrinsic(extrinsic, wait_for_inclusion=True)

All these calls will result in `1002 wasm trap` error.

**Comment by arjanz** [comment]
@pmensik it seems there is an issue with automatic decoding of SS58-formatted addresses. When the raw public key is passed in hex format, it seems to work:

```python
proxy_call = substrate.compose_call(
    call_module   = "Proxy",
    call_function = "proxy",
    call_params   = {
      "real":             f'0x{substrate.ss58_decode("HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F")}',
      "force_proxy_type": None,
      "call":             unbond_call
    }
  )
```

Could you confirm if this is also the case for you?

**Comment by pmensik** [comment]
@arjanz Thanks for the fix, just tested it and unfortunately getting 
```
ERROR:root:		Proxy call failed: {'code': 1002, 'message': 'Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0xa76f - staging_kusama_runtime.wasm!rust_begin_unwind\n    1: 0x36d2 - staging_kusama_runtime.wasm!core::panicking::panic_fmt::hcb836b5f7a10d66c\n    2: 0x5d3a7e - staging_kusama_runtime.wasm!TaggedTransactionQueue_validate_transaction', 'data': 'RuntimeApi("Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\\nWASM backtrace:\\nerror while executing at wasm backtrace:\\n    0: 0xa76f - staging_kusama_runtime.wasm!rust_begin_unwind\\n    1: 0x36d2 - staging_kusama_runtime.wasm!core::panicking::panic_fmt::hcb836b5f7a10d66c\\n    2: 0x5d3a7e - staging_kusama_runtime.wasm!TaggedTransactionQueue_validate_transaction")'}
```

I left the code as it is and just changed to following like 
```
"real":             f'0x{substrate.ss58_decode("HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F")}',
```

**Comment by pmensik** [comment]
@arjanz Hello, did you happen to have time to look at the error? You can also reach me out on TG for faster debugging if you want - `pmensik` is my handle

**Comment by Nadro-J** [comment]
Using substrate-interface v1.7.11 I was able to assign a staking proxy to one of my accounts in a test environment and use the script below to issue `staking.unbond()` from the staking proxy which seemed to have worked.

![Image](https://github.com/user-attachments/assets/bb832fa7-2f2e-4d64-84b0-283da0d4613f)

shows 2 because I executed it twice
![Image](https://github.com/user-attachments/assets/2e842a1e-04b0-4f89-a0bb-b47237e6d794) 

**.env settings**
```yaml
STAKING_ADDRESS=''
PROXY_SEED=''
```

**unbond using staking proxy**
```python
from substrateinterface import SubstrateInterface, Keypair
from dotenv import load_dotenv
import os

load_dotenv()

def staking_proxy_unbond():
    try:

        with SubstrateInterface(url='ws://localhost:8001',
                                ss58_format=2,
                                type_registry_preset='kusama') as substrate:

            staking_address = os.getenv("STAKING_ADDRESS")
            staking_proxy_seed = os.getenv("PROXY_SEED")
            amount_to_unbond = 1000000000000 # 1 KSM

            staking_proxy = Keypair.create_from_mnemonic(staking_proxy_seed)

            unbond_call = substrate.compose_call(
                call_module="Staking",
                call_function="unbond",
                call_params={
                    "value": amount_to_unbond
                }
            )

            proxy_call = substrate.compose_call(
                call_module="Proxy",
                call_function="proxy",
                call_params={
                    "real": staking_address,
                    "force_proxy_type": None,
                    "call": unbond_call
                }
            )

            extrinsic = substrate.create_signed_extrinsic(
                call=proxy_call,
                keypair=staking_proxy
            )

            print("Extrinsic created:", extrinsic)

            receipt = substrate.submit_extrinsic(
                extrinsic=extrinsic,
                wait_for_inclusion=True
            )

            if receipt.is_success:
                print(f"Unbond successful!")
                print(f"Block hash: {receipt.block_hash}")
                print(f"Extrinsic hash: {receipt.extrinsic_hash}")

            else:
                print("Unbond failed!")

    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    staking_proxy_unbond()
```

**Comment by pmensik** [comment]
@Nadro-J Thank you, new version really fixes the issue!
