### ISSUE TITLE
Installing in a fresh environment shows that requests is missing in the requirements

### ISSUE THREAD

**Issue by yabirgb** [polkascan/py-substrate-interface#398]
I've created a new environment and got this error. What I did was cloning the repo and `pip install .`

```
(py-substrate-interface) ➜  py-substrate-interface git:(master) python
Python 3.11.9 (main, Jul  3 2024, 16:57:47) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from substrateinterface import Keypair
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yabirgb/work/py-substrate-interface/substrateinterface/__init__.py", line 17, in <module>
    from .base import *
  File "/Users/yabirgb/work/py-substrate-interface/substrateinterface/base.py", line 26, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by yabirgb** [comment]
Might be an issue on my side. Closing it. Checked and it doesn't pick requests event calling it manually after doing a pip install requests
