### ISSUE TITLE
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Current offset: 72 / length: 76

### ISSUE THREAD

**Issue by wikeex** [polkascan/py-substrate-interface#84]
I am writing some test code on the Westend network. The code worked a few days ago, but now there are some errors:
```
Traceback (most recent call last):
  File "C:/Users/Cwer3/PycharmProjects/polkadot/main.py", line 90, in <module>
    transfer(test2, seed2, 0.1)
  File "C:/Users/Cwer3/PycharmProjects/polkadot/main.py", line 42, in transfer
    extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)
  File "C:\Users\Cwer3\PycharmProjects\polkadot\venv\lib\site-packages\substrateinterface\base.py", line 1440, in create_signed_extrinsic
    nonce = self.get_account_nonce(keypair.public_key) or 0
  File "C:\Users\Cwer3\PycharmProjects\polkadot\venv\lib\site-packages\substrateinterface\base.py", line 1360, in get_account_nonce
    account_info = self.query('System', 'Account', [account_address])
  File "C:\Users\Cwer3\PycharmProjects\polkadot\venv\lib\site-packages\substrateinterface\base.py", line 1241, in query
    obj.decode()
  File "C:\Users\Cwer3\PycharmProjects\polkadot\venv\lib\site-packages\scalecodec\base.py", line 383, in decode
    raise RemainingScaleBytesNotEmptyException('Current offset: {} / length: {}'.format(self.data.offset, self.data.length))
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Current offset: 72 / length: 76

Process finished with exit code 1
```
These are the test code:

```python
    substrate = SubstrateInterface(
        url="ws://10.199.6.34:19944",
        ss58_format=42,
        type_registry_preset='substrate-node-template'
    )

    info = substrate.query(
        module='System',
        storage_function='Account',
        params=[account]
    )

    print(info.value['nonce']) 
    print(info.value['data']['free'])  
```

**Comment by arjanz** [comment]
If your node is a Westend node, then you're using the wrong `type_registry_preset` in the constructor. It should be `westend` or leave it blank so it would auto-discover based on the `system_chain`.

**Comment by wikeex** [comment]
Oh yes, I was forgetting. It works, Thank you!
